# Just some basic knowledge

In [1]:
import numpy as np

In [2]:
np.sqrt(18)

4.242640687119285

In [3]:
np.log(18)

2.8903717578961645

In [4]:
list = [20, 10, 50, 30, 40, 450]

In [5]:
np.mean(list)

100.0

In [6]:
np.median(list)

35.0

In [7]:
np.array([2, 3, 4])

array([2, 3, 4])

In [8]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
np.array([1, 111, 123, 121]) / 10

array([ 0.1, 11.1, 12.3, 12.1])

In [10]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [11]:
week1 = np.array([4000, 0, 2000, 0, 1200])
week2 = np.array([1000, 2000, 0, 0, 3500])

In [12]:
week1 + week2

array([5000, 2000, 2000,    0, 4700])

In [13]:
(week1 + week2) / 2

array([2500., 1000., 1000.,    0., 2350.])

In [14]:
n = np.array([[2, 5], [6, 8], [1, 3]])
n

array([[2, 5],
       [6, 8],
       [1, 3]])

In [15]:
n.ndim

2

In [16]:
n.shape

(3, 2)

In [17]:
n.size

6

In [18]:
n[0][1]

5

In [19]:
n[0:3:2]

array([[2, 5],
       [1, 3]])

In [20]:
n[::2]

array([[2, 5],
       [1, 3]])

# 2

In [22]:
marks = np.array([5, 4, 3, 5, 4, 3, 2])
marks

array([5, 4, 3, 5, 4, 3, 2])

In [23]:
marks.min()

2

In [24]:
marks.max()

5

In [25]:
marks.mean()

3.7142857142857144

In [27]:
marks.argmax()

0

In [28]:
marks.argmin()

6

In [30]:
grades = np.array([[4, 5, 4, 3, 2],
                  [3, 5, 4, 5, 5],
                  [5, 5, 4, 5, 5]])
print(grades)

[[4 5 4 3 2]
 [3 5 4 5 5]
 [5 5 4 5 5]]


In [31]:
grades.mean(axis = 1)

array([3.6, 4.4, 4.8])

In [33]:
grades.mean(axis = 0)

array([4.        , 5.        , 4.        , 4.33333333, 4.        ])

In [34]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.arange(0, 10, 3)

array([0, 3, 6, 9])

In [37]:
np.arange(0, 10, 0.25)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  , 5.25,
       5.5 , 5.75, 6.  , 6.25, 6.5 , 6.75, 7.  , 7.25, 7.5 , 7.75, 8.  ,
       8.25, 8.5 , 8.75, 9.  , 9.25, 9.5 , 9.75])

In [39]:
z = np.zeros((3, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [40]:
o = np.ones((2, 4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
eye = np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
ages = np.array([
    [23, 24, 14, 15, 19],
    [32, 54, 34, 43, 33],
    [67, 76, 65, 66, 81]
])
ages

array([[23, 24, 14, 15, 19],
       [32, 54, 34, 43, 33],
       [67, 76, 65, 66, 81]])

In [45]:
ages >= 21

array([[ True,  True, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [49]:
work = (ages >= 18) & (ages <= 60)
work

array([[ True,  True, False, False,  True],
       [ True,  True,  True,  True,  True],
       [False, False, False, False, False]])

In [50]:
work.sum()

8

In [52]:
ages[ages >= 16]

array([23, 24, 19, 32, 54, 34, 43, 33, 67, 76, 65, 66, 81])

In [53]:
ages[(ages >= 18) & (ages <= 60)]

array([23, 24, 19, 32, 54, 34, 43, 33])