# Import the data.

In [2]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
 [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
 [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
 [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
 [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
 [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
 [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
 [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
 [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
 [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
 [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
 [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
 [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
 [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
 [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])

# 1: how much people got 0 for entry exam

In [4]:
zeroed = scores == 0
zeroed.sum()

13

# 2: how much people got more than 50 points for entry exam

In [5]:
more_than_50 = scores > 50
more_than_50.sum()

64

# 3: how much people got more than 50 but less than 70

In [8]:
from_50_to_70 = (scores >= 50) & (scores <= 70)
from_50_to_70.sum()

26

# 4: group with highest mean score

In [13]:
highest_mean = scores.mean(axis=1)
highest_mean

array([32.8, 55.2, 55.4, 55.3, 50.8, 35.7, 53.4, 47.5, 37.6, 57.9, 26. ,
       55.2, 31.6, 57.4, 40.1])

In [14]:
highest_mean.argmax()

9

# 5: save non-zero scores in the "nonzero" array

In [15]:
nonzero = scores[scores > 0]
nonzero

array([ 20,  40,  56,  80,   5,  25,  27,  74,   1,  98,  67, 100,   8,
        56,  34,  82, 100,   7,  78,  54,  23,  79, 100,  42,  95,  83,
        51,  50,  47,  23, 100,  94,  25,  48,  38,  77,  90,  87,  41,
        89,  52,   5,  17,  28,  99,  32,  18,  21,  18,  29,  31,  48,
        62,  76,  22,   6,  65,  78,  43,  22,  38,  88,  94, 100,  77,
        28,  39,  41,  81,  45,  54,  98,  12,  66,  88,  44,  55, 100,
        12,  11,  17,  70,  86,  96,  56,  23,  32,  49,  70,  80,  20,
        24,  76,  50,  29,  40,   3,   2,   5,  11,  33,  63,  28,  40,
        51, 100,  98,  87,  22,  30,  16,  54,  78,  12,  25,  35,  10,
        19,  67, 100,  88,  24,  33,  47,  56,  62,  34,  77,  53,  50,
        89,  70,  72,  56,  29,  15,  20])

# 6: using the "nonzero" array, get the minimal score

In [16]:
minimal_nonzero_score = nonzero.min()
minimal_nonzero_score

1

# 7: using the "nonzero" array, save variables with value more than 80 in the "advanced" array

In [17]:
advanced = nonzero[nonzero > 80]
advanced

array([ 98, 100,  82, 100, 100,  95,  83, 100,  94,  90,  87,  89,  99,
        88,  94, 100,  81,  98,  88, 100,  86,  96, 100,  98,  87, 100,
        88,  89])

# 8: get dimentions of "advanced" array

In [21]:
advanced.ndim

1

# 9: get a shape of the array

In [20]:
advanced.shape

(28,)

# 10: get a size of the array

In [22]:
advanced.size

28

# 11: using initial data "scores", get a boolean array named "sto", where 100 is true and else is false

In [23]:
bool_array = (scores == 100)
bool_array

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, 

# 12: using initial data, print first 7 rows.

In [24]:
print(scores[0:8])

[[ 20  40  56  80   0   5  25  27  74   1]
 [  0  98  67 100   8  56  34  82 100   7]
 [ 78  54  23  79 100   0   0  42  95  83]
 [ 51  50  47  23 100  94  25  48  38  77]
 [ 90  87  41  89  52   0   5  17  28  99]
 [ 32  18  21  18  29  31  48  62  76  22]
 [  6   0  65  78  43  22  38  88  94 100]
 [ 77  28  39  41   0  81  45  54  98  12]]
